theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: ISSI-DSIC repository
logo: /assets/img/logo.jpg
favicon: /assets/img/favicon.ico
description: ISSI research group DSIC (UPV).
show_downloads: false
