title: ISSI-DSIC repository
logo: /assets/img/logo.jpg
favicon: /assets/img/favicon.ico
description: ISSI research group DSIC (UPV).
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
